#include "RadioLib.h"

Radio::Radio() {
  ModuleA = new Module(RADIOSHIELD_CS_A, RADIOSHIELD_RX_A, RADIOSHIELD_TX_A, RADIOSHIELD_INT_0, RADIOSHIELD_INT_1);
  ModuleB = new Module(RADIOSHIELD_CS_B, RADIOSHIELD_RX_B, RADIOSHIELD_TX_B, RADIOSHIELD_INT_0, RADIOSHIELD_INT_1);
}

Radio RadioShield;
